name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: iCrawl/action-tsc@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: tsc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
